# Generated by Django 5.0.1 on 2024-02-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_delivery_person',
            new_name='is_author',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pharmacist',
        ),
    ]
