# Generated by Django 5.0.1 on 2024-02-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_type_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
