# Generated by Django 5.0.1 on 2024-05-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
